resource_types:
- name: pull-request
  type: docker-image
  source:
    repository: jtarchie/pr
    tag: latest


resources:
- name: oxygen-mask
  type: git
  source:
    uri: https://github.com/tredfield/oxygen-mask

{{ range .repos }}
  {{ if eq .pushPullRequest "true" }}
- name: {{ .interval }}-{{ .pipeline }}-{{ .name }}
  type: time
  source:
    interval: {{ .interval }}
  {{ else }}
- name: pr-{{ .pipeline }}-{{ .name }}
  type: pull-request
  check_every: 1m
  source:
    repo: scpprd/{{ .name }}
    uri: git@github.com:scpprd/{{ .name }}.git
    base: {{ .baseBranch }}
    access_token: ((github.access-token))
    private_key: ((github.private-key))
    base_url: ((concourse.base-url))
  {{ end }}

- name: git-{{ .pipeline }}-{{ .name }}
  type: git
  check_every: 2m
  source:
    uri: git@github.com:scpprd/{{ .name }}.git
    branch: {{ .baseBranch }}
    private_key: ((github.private-key))
{{ end }}

jobs:

{{ range .repos }}
- name: measure-pull-request-{{ .pipeline }}-{{ .name }}
  public: true
  max_in_flight: 1
  build_logs_to_retain: 20
  serial: true
  plan:
    - get: oxygen-mask
  {{ if eq .pushPullRequest "true" }}
    - get: {{ .interval }}-{{ .pipeline }}-{{ .name }}
      trigger: true
    - task: push-pull-request
      file: oxygen-mask/ci/push-commit.yml
      params:
        CONCOURSE_TARGET_URL: ((concourse_target_url))
        CONCOURSE_TARGET_TEAM: {{ .team }}
        CONCOURSE_TARGET_PIPELINE: {{ .pipeline }}
        REPO: {{ .name }}
        METRICS_BASE: {{ .baseBranch }}
  {{ else }}
    - get: pr-{{ .pipeline }}-{{ .name }}
      trigger: true
    - task: get-pull-request
      file: oxygen-mask/ci/get-pull-request.yml
      input_mapping:
        pull-request: pr-{{ .pipeline }}-{{ .name }}
      params:
        REPO: {{ .name }}
  {{ end }}
    - task: get-pr-status-and-emit-metrics
      file: oxygen-mask/ci/get-pr-status.yml
      params:
        CONCOURSE_TARGET_URL: ((concourse_target_url))
        CONCOURSE_TARGET_TEAM: {{ .team }}
        CONCOURSE_TARGET_PIPELINE: {{ .pipeline }}
        REPO: {{ .name }}
        MANIFEST_REPO: {{ .manifestRepoName }}
        METRICS_BASE: {{ .baseBranch }}
    - task: merge-pull-request
      file: oxygen-mask/ci/merge-pull-request.yml
      params:
        REPO: {{ .name }}
        DO_MERGE: {{ .pushPullRequest }}

- name: measure-build-{{ .pipeline }}-{{ .name }}
  public: true
  max_in_flight: 1
  build_logs_to_retain: 20
  serial: true
  plan:
    - get: oxygen-mask
    - get: git-{{ .pipeline }}-{{ .name }}
      trigger: true
    - task: emit-build-metrics
      file: oxygen-mask/ci/emit-build-metrics.yml
      params:
        CONCOURSE_TARGET_URL: ((concourse_target_url))
        CONCOURSE_TARGET_TEAM: {{ .team }}
        CONCOURSE_TARGET_PIPELINE: {{ .pipeline }}
        REPO: {{ .name }}
        MANIFEST_REPO: {{ .manifestRepoName }}
        METRICS_BASE: {{ .baseBranch }}
      input_mapping:
        git-repo: git-{{ .pipeline }}-{{ .name }}
  {{ if eq .pushPullRequest "true" }}
    - task: clean-up
      file: oxygen-mask/ci/clean-up.yml
      params:
        CONCOURSE_TARGET_URL: ((concourse_target_url))
        CONCOURSE_TARGET_TEAM: {{ .team }}
        CONCOURSE_TARGET_PIPELINE: {{ .pipeline }}
        REPO: {{ .name }}
        METRICS_BASE: {{ .baseBranch }}
  {{ end }}

{{ end }}
