// create a pr commit

resource_types:


jobs:

- name: measure-pull-request
  public: true
  max_in_flight: 1
  plan:

    // submit a pull-request

    // emit start metric

    // poll for status and emit finish metric
